server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 10
    maxWait: 60000     #获取连接时最大等待时间，单位毫秒
    timeBetweenEvictionRunsMillis: 1800000     #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    filters: stat,wall,slf4j    #通过别名的方式配置扩展插件，常用的插件有：监控统计用的filter:stat，日志用的filter: slf4j，防御sql注入的filter:wall
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=90;druid.stat.logSlowSql=true   # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    validationQuery: select 'x'   #用来检测连接是否有效的sql，要求是一个查询语句
    testWhileIdle: true       #建议配置为true，不影响性能，并且保证安全性。如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
    testOnBorrow: false       #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    testOnReturn: false       #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    poolPreparedStatements: false #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭

