server:
  port: 8083
  servlet:
    # 应用的访问路径
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/new_sqjz?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: '0519'
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 10
    maxWait: 60000     #获取连接时最大等待时间，单位毫秒
    timeBetweenEvictionRunsMillis: 1800000     #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    filters: stat,wall,slf4j    #通过别名的方式配置扩展插件，常用的插件有：监控统计用的filter:stat，日志用的filter: slf4j，防御sql注入的filter:wall
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=90;druid.stat.logSlowSql=true   # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    validationQuery: select 'x'   #用来检测连接是否有效的sql，要求是一个查询语句
    testWhileIdle: true       #建议配置为true，不影响性能，并且保证安全性。如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
    testOnBorrow: false       #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    testOnReturn: false       #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    poolPreparedStatements: false #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.johnyehyo.base.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mapper/mybatis-config.xml

token:
  # 令牌自定义标识
  header: Authorization
  # 令牌秘钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30
